readthedocs/sphinx-hoverxref

hoverxref/extension.py

Read the Docs uses its own HTML dir builder. This PR overrides this builder as we are doing with `readthedocs` to save the metadata into its nodes as well.

Override `readthedocsdirhtml` as well

---

tox.ini

Added Python 3.8 and Sphinx 2.3.1

Test more Python & Sphinx versions

---

docs/conf.py

I'm using `LOCAL_READTHEDOCS` env variable to build it and develop
locally while using the same set of docs comming from this repo.
Now, I'm pointing `tooltip_api_host` to our new docker-compose configuration.

Use URL for docker-compose instance when building locally

---

MANIFEST.in

When building the package these themes were not included and were
impossible so select via the config option.

Include other tooltipster themes in package

---

docs/conf.py
docs/configuration.rst
docs/index.rst
hoverxref/domains.py
hoverxref/extension.py
tests/test_htmltag.py

Avoid conflict with `hoverxref_default_type` (without s), and I think
it communicate better what it is. A mapping between role -> type

Rename hoverxref_default_types to hoverxref_role_types

---

hoverxref/domains.py
tests/examples/default/index.rst
tests/test_internals.py

It does not make sense to override the domain classes when using other non-HTML builders because there is nothing to add.
Although, due to a initialization race condition, we are not able to "not override the Domains if the builder is non-HTML" so we need to skip our custom resolution during build time.
**NOTE:** I'm not happy with this solution. I would like to find a way to _not_ override the Domains if we already know that the builder is `html`.
> This PR is based on #60 --so, if that one is merged first, we need to change the base before merging.
Closes #62

Ignore references in non-HTML builders

---

docs/configuration.rst
hoverxref/domains.py
hoverxref/extension.py

Do not log warnings unless strictly needed because otherwise it breaks CIs.
Besides, I'm lowering down a logging level for debugging output.
Closes #59

Reduce one logging level

---

hoverxref/domains.py
hoverxref/extension.py
tests/conftest.py
tests/examples/default/conf.py
tests/examples/default/index.rst
tests/test_htmltag.py
tests/test_internals.py
tests/utils.py

We set our own translator in the translators defined by other extensions, but
also for the current builder.
It may happen that there is an extension that defines two translators for
`dirhml` and `json`, and we are going to override them --the problem comes when
`sphinx-build` is called with `-b custombuilder` since we weren't overriding it
in that case.
This commit override the ones defined by the user, but also the default one.
**NOTE:** the diff is a little tricky. I only removed an indentation level (to remove the first if) and swap the for/if blocks. There is no other changes.

Translator on current builder

---

docs/configuration.rst
hoverxref/domains.py
hoverxref/utils.py
tests/examples/custom-object/code.rst
tests/examples/custom-object/conf.py
tests/examples/custom-object/index.rst
tests/test_htmltag.py

Support tooltips in :numref:

---

hoverxref/_static/js/hoverxref.js_t
tests/test_htmltag.py

EmbedAPI is expecting `path`, and we were sending `docpath`. This made all the links from inside the tooltip to return 404.
This was a regression introduced at b92ac36d652eeeec997e330017288d933bf002a4
@Daltz333 @Zac-HD would you please, test this PR in your documentation and let me know if this fixes your issue?
Closes #75

Send `path` instead of `docpath`

---

docs/conf.py

This is useful to avoid CORS or to use Read the Docs for Business.

Use proxied API endpoint

---

hoverxref/_static/js/hoverxref.js_t

I'm surprised it was this simple. I don't think MathJax actually exposes a way in their API to get the current version, so I'm not sure how to make this call conditional.
Closes #85

Add MathJax3 Compatability 

---

docs/requirements.txt

Sphinx 3.5.x includes a feature to only include the JS and CSS on the pages that
they are used. This conflicts when we render content that uses MathJax, since
the page that shows the tooltip does not has MathJax loaded, but the content
rendered inside the tooltip requires it to work.
See https://github.com/sphinx-doc/sphinx/pull/8631

Use Sphinx 3.4.x to build the docs

---

docs/usage.rst

Mention that when using Sphinx>=3.5 content with MathJax or sphinx-tabs won't
work due to a new feature included in that release of Sphinx.
Closes #123

Docs: mention that Sphinx>=3.5 may not work with dynamic content

---

docs/requirements.txt
hoverxref/_static/js/hoverxref.js_t

Use two different selectors for sphinx-tabs<2 and >=2:
- `sphinx_tabs/tabs.js`
- `_static/tabs.js`
If the first one is used, the old code that adds a `script` tag is used. If the second one (sphinx-tabs>=2) is found, we call a small chunk of code to enable the tabs.
Closes #104

Update `sphinx-tabs` to its latest version

---

.readthedocs.yml
docs/conf.py
docs/configuration.rst
docs/usage.rst
hoverxref/_static/js/hoverxref.js_t
hoverxref/extension.py
tests/conftest.py
tests/examples/intersphinx/conf.py
tests/examples/intersphinx/index.rst
tests/test_htmltag.py
tests/utils.py
tox.ini

Just an idea of what we can do to support intersphinx in this extension. There are different things to coordinate and decide yet, but I wanted to have something working to see how it could fit.
> **Rendered version** with an example: 
> https://sphinx-hoverxref--86.org.readthedocs.build/en/86/usage.html#tooltip-on-intersphinx-content 
Intersphinx subscribes to `missing-reference` event to use different methods to try to resolve the reference. If it succeed by using one of the intersphinx configurations (from `intersphinx_mapping` config) it returns a `nodes.reference`. As we can't hook into the middle of that function, we disconnect the original function called on `missing-reference` event and we connect a custom one. There we call the original function and add some extra data (CSS …

Intersphinx support

---

docs/usage.rst
hoverxref/extension.py

Tell Sphinx to always include assets in all HTML pages
Closes #119

Use `app.set_html_assets_policy` as `'always'`

---

hoverxref/_static/js/hoverxref.js_t

It doesn't make sense the browser shows the default tooltip (browser's built-in)
and immediately after that our tooltip was shown.
This commit removes the `title=` property for all intersphinx links where
hoverxref was enabled.
Closes #133

Remove `title=` for intersphinx (external links) with hoverxref

---

hoverxref/_static/js/hoverxref.js_t
hoverxref/extension.py
tests/test_htmltag.py

Send `X-HoverXRef-Version` to know that the EmbedAPI is used by this
extension and what version in particular.
It seems that modifying the `User-Agent` is not allowed and it's not preferable
anyways. Knowing the `User-Agent` together with the sphinx-hoverxref version is
good data to have.
Requires #158 for the tests to pass.

Send custom HTTP header

---

.circleci/config.yml
tox.ini

- pin docutils<0.18 on some Sphinx versions
- use Python 3.10 to run the test suite
- refactor CircleCI to use parameters
- remove old environment variables on docs env

Update test suite: run Python 3.10

---

hoverxref/_static/js/hoverxref.js_t
tests/test_htmltag.py

Since `.ajaxSetup` works globally, it was interfering with other `.ajaxSetup`
being called in other plugins.
Closes #165

Ajax header: send the header on each call instead with .ajaxSetup

---

hoverxref/extension.py
tests/examples/intersphinx/index.rst
tests/test_htmltag.py

We were generating the inventory's key manually based on the `reftype` and
fallbacks. However, we weren't covering all the possible cases. This commit,
uses `.objtypes_for_role` domain's method to get all the possible names for a
particular `reftype` on a domain.
With this change, it also adds supports for generic `obj` type in a domain,
making our code to find all the possible alternative keys in that particular
domain. This is useful when using `default_role = 'obj'` as requested in
https://github.com/readthedocs/sphinx-hoverxref/issues/170
Closes #170

Intersphinx: improve robustness

---

.circleci/config.yml
tox.ini

- remove Python 3.6 and 3.7
- add Sphinx versions 4.4, 4.5 and 5.0
- pin Jinja2 to <3.0.3 for older Sphinx versions

Test: update testing versions

---

docs/conf.py

We don't really need this change for sphinx-hoverxref itself, but it seems this
helps package maintainers when building and packaging this extension.
Closes #178

Packaging: be more friendly with package maintainers

---

hoverxref/extension.py
tests/examples/python-domain/index.rst
tests/test_htmltag.py

Skip the node in case the `reftype` is not defined for the particular domain we
are checking for.
Closes #192

Intersphinx and Python domain

---

docs/development.rst

Small tip to document steps to hit a local development instance from an online
documentation site we don't have control. This is useful to test a new change in
the backend that's not deployed yet.

Development: tip to hit local instance from online documentation

---

hoverxref/_static/css/tooltipster.custom.css
hoverxref/_static/css/tooltipster.custom.css_t
hoverxref/_static/js/hoverxref.js_t
hoverxref/domains.py
hoverxref/extension.py
tests/test_htmltag.py

Avoid collisions with other CSS frameworks/themes/etc.
See https://github.com/executablebooks/sphinx-book-theme/issues/577
Closes #180

Prefix all CSS classes with `hxr-`

---

hoverxref/extension.py

While using `setuptools` documentation project as example I found this error
case. I'm not sure why it's happening, but I'm considering it an edge case for
now and ignoring these nodes
Node content:
```
{'rawsource': '`the PyPA
Specification\n<PyPUG:specifications/declaring-project-metadata>`', 'children':
[<literal: <#text: 'the PyPA Speci ...'>>], 'attributes': {'ids': [], 'classes':
[], 'names': [], 'dupnames': [], 'backrefs': [], 'refdoc': 'history',
'refdomain': '', 'reftype': 'any', 'refexplicit': True, 'refwarn': True,
'reftarget': 'PyPUG:specifications/declaring-project-metadata'}, 'tagname':
'pending_xref', 'source': '../CHANGES (links).rst', 'line': 328, 'parent':
<paragraph: <#text: 'Please note th ...'><literal...><#text: ' file  ...>}
```
Full traceback:
```
Traceback (most …
```

Intersphinx: ignore nodes without domain

---

docs/requirements.txt
hoverxref/extension.py
pyproject.toml

Sphinx 6.x is removing jQuery. So, we need to manually add it.
Closes #160 
Based on https://github.com/readthedocs/readthedocs.org/pull/9665/
----
:books: Documentation preview :books:: https://sphinx-hoverxref--241.org.readthedocs.build/en/241/
----
:books: Documentation preview :books:: https://read-the-docs-sphinx-hoverxref--241.com.readthedocs.build/en/241/

Make usage of `sphinxcontrib-jquery`

---

hoverxref/extension.py
tests/examples/intersphinx/index.rst
tests/test_htmltag.py

Intersphinx supports explicitly specifying the inventory name in a link target, e.g. the `python:` part in ``:ref:`python:datetime-datetime` ``.
The custom `missing_reference` hook in hoverxref handles such target names as well, but only in the `std` domain (as far as I can tell, particularly for `:ref:`, which is in the `std` domain).
Intersphinx supports target names with explicit inventories regardless of role/domain, which means ``:py:attr:`python:datetime.time.minute` `` results in the correct link, but without the hoverxref popup as the `python:` prefix isn't handled by hoverxref in this case.
---
This PR attempts to fix this by removing the check for the `std` domain, which I believe intersphinx also [doesn't check](https://github.com/sphinx-doc/sphinx/blob/4d90277c/sphinx/ext/inter …

Handle explicit intersphinx inventory names in all domains

---

pyproject.toml

This should install the proper version of `docutils` without finding any incompatibility.

Requirements: unpin sphinx-tabs

---

.github/workflows/pr-preview-links.yaml

The .com link is invalid? There are no builds there.
I also noticed a case of "race condition" in the editing which illustrates how we need to change the Action's URL feedback as a comment, rather than editing the PR description.
In one PR, only the .com link was present:
But looking around at other PRs, both links usually show up.
----
:books: Documentation preview :books:: https://sphinx-hoverxref--262.org.readthedocs.build/en/262/
----
:books: Documentation preview :books:: https://read-the-docs-sphinx-hoverxref--262.com.readthedocs.build/en/262/

Remove RTD .com preview from pr-preview-links.yaml

---

docs/requirements.txt
pyproject.toml

Closes #280
Versions lower than 0.20 cause rendering problems in the usage page with the bibliography, see #280.
----
📚 Documentation preview 📚: https://sphinx-hoverxref--281.org.readthedocs.build/en/281/

Dependencies: add minimum docutils version

---

README.rst

----
📚 Documentation preview 📚: https://sphinx-hoverxref--291.org.readthedocs.build/en/291/

fix(docs): remove outdated travis build status badge

---

hoverxref/extension.py
tests/test_internals.py
tox.ini

Hi hoverxref team,
My tooltips on intersphinx projects stopped working recently. After a while I was able to track down that the break started happening on [`sphinx-7.4.0`](https://www.sphinx-doc.org/en/master/changes/7.4.html).
It seems to be due to `sphinx.ext.intersphinx` becoming a package since that version (through https://github.com/sphinx-doc/sphinx/pull/12178, undocumented in the changelog), so I've updated [`setup_intersphinx`](https://github.com/chrizzFTD/sphinx-hoverxref/blob/65524c4d45a92aa49da5c0fb22483163165c5b25/hoverxref/extension.py#L160) to check for a prefix in the module name, which should preserve backwards compatibility.
Please let me know your thoughts!
To see in action, the `See also` links from [grill.cook.UsdAsset](https://grill--40.org.readthedocs.build/en/40/ap …

Update compatibility of setup_intersphinx module name check with Sphinx-7.4

---

hoverxref/extension.py

We are disconnecting the html-page-context event from sphinx-tabs, which was used to delete the static files from html files that didn't use sphinx-tabs. But in https://github.com/executablebooks/sphinx-tabs/pull/198 this was changed to instead decide if the page should have the static files or not.
Since we are removing that event, sphinx-tabs never gets to inject the static files, this breaks sphinx-tabs for projects using hoverxref.
We no longer need to disconnect that signal, since we are overriding the html assets policy to `always`, which sphnx-tabs respects already https://github.com/executablebooks/sphinx-tabs/pull/132 (more than 3 years ago).
----
📚 Documentation preview 📚: https://sphinx-hoverxref--318.org.readthedocs.build/en/318/

Don't disconnect html-page-context event from sphinx-tabs

---

CHANGELOG.rst
hoverxref/__init__.py
pyproject.toml

----
📚 Documentation preview 📚: https://sphinx-hoverxref--320.org.readthedocs.build/en/320/

Release 1.4.2

---

hoverxref/extension.py

Fixes https://github.com/readthedocs/sphinx-hoverxref/issues/312.
----
📚 Documentation preview 📚: https://sphinx-hoverxref--313.org.readthedocs.build/en/313/

Fix _Opt deprecation warnings
